apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-script
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  init.sh: |
    #!/bin/sh
    # Wait for PowerDNS to be ready
    until curl -s -H 'X-API-KEY: {{ .Values.apiPassword }}' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      "http://{{ include "app.FQDN" . }}/api/v1/servers/localhost/zones"; do
      echo "Waiting for pdns to be ready..."
      sleep 1
    done
    {{- range .Values.pdns.zones }}
    curl -v -X POST -H 'X-API-KEY: {{ $.Values.apiPassword }}' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{"name": "{{ . }}.", "kind": "Native", "masters": [], "nameservers": ["ns1.{{ . }}.", "ns2.{{ . }}."]}' \
      "http://{{ include "app.FQDN" $ }}/api/v1/servers/localhost/zones"
    curl -v -X PATCH -H 'X-API-KEY: {{ $.Values.pdns.apiPassword }}' \
      -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{"rrsets":[{"changetype":"REPLACE","name":"{{ . }}.","records":[{"content":"ns1.{{ . }}. hostmaster.{{ . }}. 0 300 300 300 300","disabled":false}],"ttl":300,"type":"SOA"}]}' \
      "http://{{ include "app.FQDN" $ }}/api/v1/servers/localhost/zones/{{ .}}"
    {{- end }}
    echo "Initialization script completed."
